name: Capture Screenshot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: screenshots
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install puppeteer sharp
        
      - name: Create screenshots directory
        run: mkdir -p screenshots
        
      - name: Capture screenshot
        run: node .github/scripts/screenshot.js
        
      - name: List files
        run: |
          echo "Current directory structure:"
          tree || ls -R
          echo "Screenshots directory contents:"
          ls -la screenshots/
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Add all jpg files in screenshots directory
          git add screenshots/*.jpg
          
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Update screenshots $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Push if there are commits to push
          git push origin screenshots 
