name: Capture Screenshots

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Manual trigger

jobs:
  capture:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: screenshots
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - run: npm install puppeteer sharp
      
      - run: mkdir -p screenshots
      
      - name: Capture screenshots
        run: |
          node .github/scripts/screenshot.js
          echo "Screenshot directory contents:"
          ls -la screenshots/
      
      - name: Commit and push if changed
        run: |
          git confi
